autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

onlyBuiltDependencies:
  - esbuild

overrides:
  chalk-template@1.1.1: '>=1.1.2'
  chalk@5.6.1: '>=5.6.2'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'

strictPeerDependencies: false
