onlyBuiltDependencies:
  - esbuild

enablePrePostScripts: true
legacyPeerDeps: true
autoInstallPeers: true
strictPeerDependencies: false

overrides:
  chalk@<5.6.2: '>=5.6.2'
  chalk-template@<1.1.2: '>=1.1.2'
