name: auto-merge
 
on:
  pull_request:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - name: Pull request auto merge enabler
      uses: poad/github-pull-request-auto-merge-enable-action@v1.0.5
      with:
        pull_request_number: ${{ github.event.pull_request.number }}
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        repository: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        merge_method: SQUASH
